name: API and Web UI Automation Pipeline (Optimized)

# Trigger pipeline hanya pada push ke main untuk menghemat minutes
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Combined job untuk menghemat minutes
  automation-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install
        
    - name: Run API Tests
      run: |
        npm run test:api || true
        
    - name: Install Playwright Browsers (if needed)
      run: |
        npx playwright install --with-deps chromium || true
        
    - name: Run UI Tests (Chrome only untuk menghemat waktu)
      run: |
        npx playwright test --project=chromium || true
        
    - name: Generate Test Reports
      run: |
        npm run test:api:report || true
        npm run test:ui:report || true
        
    # Upload hanya results penting
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          test-results/
          reports/
          playwright-report/
        retention-days: 7  # Kurangi retention untuk menghemat storage
        
  # Job terpisah untuk security (optional, jalankan manual)
  security-testing:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: automation-tests
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run Basic Security Checks
      run: |
        echo "Running basic security checks..."
        # Implementasi security check sederhana
        npm audit --audit-level=high || true
